apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
      app: kuard
      version: "2"
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:2
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
